version: '3.8'

services:
  tts-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/mozilla_tts
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
